name: CI/CD
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Build and unit test our code"
      
  pr:
    runs-on: ubuntu-latest
    if: github.event.number != null #  this only runs when in a PR
    needs: [build]
    steps:
    - run: echo "Deploy code to PR#${{ github.event.number }}"
    - name: Log into Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_SP }} 
    - name: Create new PR environment and deploy code
      run: az group create --name "MyApplicationPR${{ github.event.number }}" --location eastus
      shell: pwsh

  dev:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # only run on the main trunk
    needs: [build]
    steps:
    - run: echo "Deploy code to dev"
    - name: Log into Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_SP }} 
    - name: Create new Dev environment and deploy code
      run: az group create --name MyApplicationDev --location eastus
      shell: pwsh


  qa:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # only run on the main trunk
    needs: [dev]
    steps:
    - run: echo "Deploy code to qa"
    - name: Log into Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_SP }} 
    - name: Create new QA environment and deploy code
      run: az group create --name MyApplicationQA --location eastus
      shell: pwsh
 
 
  prod:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # only run on the main trunk
    needs: [qa]
    steps:
    - run: echo "Deploy code to production"
    - name: Log into Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_SP }} 
    - name: Create new Prod environment and deploy code
      run: az group create --name MyApplicationProd --location eastus
      shell: pwsh
 
