name: CI/CD
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs: 
  pr:
    runs-on: ubuntu-latest
    if: github.event.number != null #  this only runs when in a PR
    steps:
    - run: |
        echo "Deploy code to PR#${{ github.event.number }}"

  dev:
    runs-on: ubuntu-latest
    if: github.event.number == null #Should be nothing, as this doesn't run on a PR
    steps:
    - run: |
        echo "Deploy code to dev"


  qa:
    runs-on: ubuntu-latest
    if: github.event.number == null #Should be nothing, as this doesn't run on a PR
    steps:
    - run: |
        echo "Deploy code to qa"
 
 
  prod:
    runs-on: ubuntu-latest
    if: github.event.number == null #Should be nothing, as this doesn't run on a PR
    steps:
    - run: |
        echo "Deploy code to production"
 
