name: CI/CD
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs: 
  pr:
    runs-on: ubuntu-latest
    if: github.event.number != null #  this only runs when in a PR
    steps:
    - run: |
        echo "Deploy code to PR#${{ github.event.number }}"
    - name: Log into Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_SP }} 
    - run: az group create --name "MyApplicationPR${{ github.event.number }}" --location eastus
      shell: pwsh

  dev:
    runs-on: ubuntu-latest
    if: github.event.number == null #Should be nothing, as this doesn't run on a PR
    steps:
    - run: |
        echo "Deploy code to dev"
    - name: Log into Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_SP }} 
    - run: az group create --name MyApplicationDev --location eastus
      shell: pwsh


  qa:
    runs-on: ubuntu-latest
    if: github.event.number == null #Should be nothing, as this doesn't run on a PR
    steps:
    - run: |
        echo "Deploy code to qa"
    - name: Log into Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_SP }} 
    - run: az group create --name MyApplicationQA --location eastus
      shell: pwsh
 
 
  prod:
    runs-on: ubuntu-latest
    if: github.event.number == null #Should be nothing, as this doesn't run on a PR
    steps:
    - run: |
        echo "Deploy code to production"
    - name: Log into Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_SP }} 
    - run: az group create --name MyApplicationProd --location eastus
      shell: pwsh
 
