name: CI/CD
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs: 
  pr:
    runs-on: ubuntu-latest
    env:
      PR_NUMBER: ${{ github.event.number }}
    if: github.event.number != null
    steps:
    - run: |
        echo "GITHUB_REF: $GITHUB_REF"
        echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
        echo "PR #: ${{ env.PR_NUMBER }}"

  dev:
    runs-on: ubuntu-latest
    env:
      PR_NUMBER: ${{ github.event.number }}
    if: github.event.number == null
    steps:
    - run: |
        echo "GITHUB_REF: $GITHUB_REF"
        echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
        echo "PR #: ${{ env.PR_NUMBER }}"
