name: CI/CD
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs: 
  pr:
    runs-on: ubuntu-latest
    #env:
    #  prId: 000
    #  prUC: PR${{ env.prId }}
    #  prLC: pr${{ env.prId }}
    #if: (success() && (variables['Build.Reason'] == 'PullRequest') && (variables['System.PullRequest.PullRequestId'] != 'Null'))
    steps:
    - run: |
        echo "ref: $github.ref"
        echo "GITHUB_WORKSPACE: $github.workspace"
        #prId: "$(System.PullRequest.PullRequestId)"
        # if eq(variables['Build.SourceBranchName'], 'master')
        #prId: '000'
